// Canvas template presets - Fabric.js object configurations
// IDs match the gallery template IDs for seamless integration
export interface TemplatePreset {
  id: string
  name: string
  category: string
  canvasSize: { width: number; height: number }
  objects: any[] // Fabric.js serialized objects
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  // Partnership templates
  {
    id: 'partnership-horizontal',
    name: 'Partnership Horizontal',
    category: 'Co-Marketing',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 200,
        top: 490,
        scaleX: 1.5,
        scaleY: 1.5,
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 300,
        top: 490,
        fontSize: 42,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: '×',
        left: 540,
        top: 490,
        fontSize: 36,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '300',
        fill: '#666666',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'Partner',
        left: 620,
        top: 490,
        fontSize: 42,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originY: 'center',
      },
    ],
  },
  {
    id: 'partnership-card',
    name: 'Partnership Card (Vertical)',
    category: 'Co-Marketing',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 540,
        top: 300,
        scaleX: 2,
        scaleY: 2,
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 540,
        top: 400,
        fontSize: 48,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: '×',
        left: 540,
        top: 500,
        fontSize: 32,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '300',
        fill: '#666666',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'Partner',
        left: 540,
        top: 600,
        fontSize: 48,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
    ],
  },
  
  // Hero/Announcement templates
  {
    id: 'hero-deep-gradient',
    name: 'Hero Clean',
    category: 'Announcements',
    canvasSize: { width: 1200, height: 675 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1200,
        height: 675,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 560,
        top: 180,
        scaleX: 0.8,
        scaleY: 0.8,
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 640,
        top: 180,
        fontSize: 28,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        fill: '#FFFFFF',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'What is the EIL?',
        left: 600,
        top: 340,
        fontSize: 72,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'Subtitle goes here',
        left: 600,
        top: 420,
        fontSize: 24,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fill: '#888888',
        originX: 'center',
        originY: 'center',
      },
    ],
  },
  {
    id: 'mountain-landscape',
    name: 'Mountain Landscape',
    category: 'Announcements',
    canvasSize: { width: 1200, height: 675 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1200,
        height: 675,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 60,
        top: 60,
        scaleX: 1.2,
        scaleY: 1.2,
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 130,
        top: 68,
        fontSize: 24,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        fill: '#FFFFFF',
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 600,
        top: 300,
        fontSize: 80,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'Your multichain crypto home base',
        left: 600,
        top: 380,
        fontSize: 28,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fill: '#CCCCCC',
        originX: 'center',
        originY: 'center',
      },
    ],
  },
  
  // Stats/Milestone templates
  {
    id: 'stats-milestone-3d',
    name: 'Stats Milestone',
    category: 'Metrics',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 540,
        top: 250,
        scaleX: 1.2,
        scaleY: 1.2,
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: '779,387',
        left: 540,
        top: 480,
        fontSize: 120,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'txns',
        left: 540,
        top: 560,
        fontSize: 48,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '600',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'We just hit an all-time record in a single day.',
        left: 540,
        top: 650,
        fontSize: 22,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fill: '#888888',
        originX: 'center',
        originY: 'center',
      },
    ],
  },
  {
    id: 'stats-mountain',
    name: 'Stats Mountain',
    category: 'Metrics',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 540,
        top: 300,
        scaleX: 1.5,
        scaleY: 1.5,
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: '$2.5B+',
        left: 540,
        top: 500,
        fontSize: 100,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'Total Volume',
        left: 540,
        top: 600,
        fontSize: 32,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fill: '#888888',
        originX: 'center',
        originY: 'center',
      },
    ],
  },
  
  // Event templates
  {
    id: 'event-announcement',
    name: 'Event Announcement',
    category: 'Events',
    canvasSize: { width: 1200, height: 675 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1200,
        height: 675,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 80,
        top: 50,
        scaleX: 0.8,
        scaleY: 0.8,
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 140,
        top: 58,
        fontSize: 18,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        fill: '#FFFFFF',
      },
      {
        type: 'i-text',
        text: 'January 29th, Berlin',
        left: 1120,
        top: 58,
        fontSize: 16,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fill: '#888888',
        originX: 'right',
      },
      {
        type: 'i-text',
        text: 'Hyperliquid Deutschland',
        left: 80,
        top: 450,
        fontSize: 64,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
      },
      {
        type: 'i-text',
        text: 'Come meet us!',
        left: 80,
        top: 530,
        fontSize: 28,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fill: '#888888',
      },
    ],
  },
  
  // UI/Product templates
  {
    id: 'ui-showcase',
    name: 'UI Showcase',
    category: 'Product',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'i-text',
        text: 'ShapeShift Deposit',
        left: 50,
        top: 50,
        fontSize: 32,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
      },
      {
        type: 'i-text',
        text: 'One Click Deposits. From Anywhere',
        left: 50,
        top: 95,
        fontSize: 16,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fill: '#888888',
      },
      {
        type: 'rect',
        left: 340,
        top: 300,
        width: 400,
        height: 600,
        fill: '#1a1a1a',
        rx: 24,
        ry: 24,
        originX: 'center',
        originY: 'center',
        stroke: '#333333',
        strokeWidth: 2,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 50,
        top: 1000,
        scaleX: 0.6,
        scaleY: 0.6,
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 95,
        top: 1008,
        fontSize: 15,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        fill: '#FFFFFF',
      },
    ],
  },
  
  // Community templates
  {
    id: 'fox-moon',
    name: 'Fox Moon',
    category: 'Community',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#1a1f2e',
        selectable: false,
        evented: false,
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 920,
        top: 50,
        fontSize: 18,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        fill: '#FFFFFF',
        originX: 'right',
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 1030,
        top: 42,
        scaleX: 0.7,
        scaleY: 0.7,
        originX: 'right',
      },
      {
        type: 'i-text',
        text: 'Building the future',
        left: 50,
        top: 850,
        fontSize: 56,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
      },
      {
        type: 'i-text',
        text: 'of finance',
        left: 50,
        top: 920,
        fontSize: 56,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#3B82F6',
      },
      {
        type: 'i-text',
        text: 'Your Keys. Your Crypto.',
        left: 50,
        top: 1020,
        fontSize: 13,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fill: '#888888',
      },
    ],
  },
]
