// Canvas template presets - Fabric.js object configurations
export interface TemplatePreset {
  id: string
  name: string
  category: string
  canvasSize: { width: number; height: number }
  objects: any[] // Fabric.js serialized objects
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    id: 'partnership-horizontal',
    name: 'Partnership Horizontal',
    category: 'Co-Marketing',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 200,
        top: 490,
        scaleX: 1.5,
        scaleY: 1.5,
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 300,
        top: 490,
        fontSize: 42,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: '×',
        left: 540,
        top: 490,
        fontSize: 36,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '300',
        fill: '#666666',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'Partner',
        left: 620,
        top: 490,
        fontSize: 42,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originY: 'center',
      },
    ],
  },
  {
    id: 'partnership-vertical',
    name: 'Partnership Vertical',
    category: 'Co-Marketing',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 540,
        top: 300,
        scaleX: 2,
        scaleY: 2,
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 540,
        top: 400,
        fontSize: 48,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: '×',
        left: 540,
        top: 500,
        fontSize: 32,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '300',
        fill: '#666666',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'Partner',
        left: 540,
        top: 600,
        fontSize: 48,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
    ],
  },
  {
    id: 'announcement-hero',
    name: 'Announcement Hero',
    category: 'Announcements',
    canvasSize: { width: 1200, height: 675 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1200,
        height: 675,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 80,
        top: 50,
        scaleX: 0.8,
        scaleY: 0.8,
      },
      {
        type: 'i-text',
        text: 'Big Announcement',
        left: 600,
        top: 300,
        fontSize: 72,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'Subtitle goes here',
        left: 600,
        top: 380,
        fontSize: 28,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fill: '#888888',
        originX: 'center',
        originY: 'center',
      },
    ],
  },
  {
    id: 'stats-milestone',
    name: 'Stats Milestone',
    category: 'Metrics',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 540,
        top: 250,
        scaleX: 1.2,
        scaleY: 1.2,
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: '$2.5B+',
        left: 540,
        top: 480,
        fontSize: 120,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'Total Volume',
        left: 540,
        top: 580,
        fontSize: 32,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fill: '#888888',
        originX: 'center',
        originY: 'center',
      },
    ],
  },
  {
    id: 'integration-live',
    name: 'Integration Live',
    category: 'Co-Marketing',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'i-text',
        text: 'NOW LIVE',
        left: 540,
        top: 200,
        fontSize: 24,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '600',
        fill: '#3B82F6',
        originX: 'center',
        originY: 'center',
        charSpacing: 200,
      },
      {
        type: 'i-text',
        text: 'Partner Name',
        left: 540,
        top: 400,
        fontSize: 64,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '800',
        fill: '#FFFFFF',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'is now available on',
        left: 540,
        top: 500,
        fontSize: 28,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fill: '#888888',
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 440,
        top: 620,
        scaleX: 1.2,
        scaleY: 1.2,
        originX: 'center',
        originY: 'center',
      },
      {
        type: 'i-text',
        text: 'ShapeShift',
        left: 580,
        top: 620,
        fontSize: 36,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        fill: '#FFFFFF',
        originY: 'center',
      },
    ],
  },
  {
    id: 'quote-card',
    name: 'Quote Card',
    category: 'Community',
    canvasSize: { width: 1080, height: 1080 },
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#0A0B0D',
        selectable: false,
        evented: false,
      },
      {
        type: 'i-text',
        text: '"',
        left: 100,
        top: 250,
        fontSize: 200,
        fontFamily: 'Georgia, serif',
        fontWeight: '400',
        fill: '#3B82F6',
      },
      {
        type: 'i-text',
        text: 'Your quote goes here.\nMake it impactful.',
        left: 120,
        top: 400,
        fontSize: 42,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '500',
        fill: '#FFFFFF',
        lineHeight: 1.4,
      },
      {
        type: 'i-text',
        text: '— Speaker Name',
        left: 120,
        top: 700,
        fontSize: 24,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        fill: '#888888',
      },
      {
        type: 'image',
        src: '/images/fox-logo.svg',
        left: 980,
        top: 980,
        scaleX: 0.8,
        scaleY: 0.8,
        originX: 'right',
        originY: 'bottom',
      },
    ],
  },
]
